# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.PCM', verbose_name='reviewer'),
        ),
    ]
